### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Syncthing/Android app strings (fork)](https://hosted.weblate.org/projects/syncthing/android/catfriend1/fork-stringsxml/).

It also includes following components:

* [Syncthing/Google Play listings (fork)](https://hosted.weblate.org/projects/syncthing/android/catfriend1/fork-play-listings/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Catfriend1** [comment]
@acolomb What do I need to set that weblate can automatically merge those PR's?

**Comment by acolomb** [comment]
I don't think it can be configured to merge pull requests. But we can make it push the commits directly to your main branch.

**Comment by Catfriend1** [comment]
@acolomb ok, let's try. What do I need to do to allow this?

**Comment by acolomb** [comment]
I'll reconfigure the Weblate project right away.

**Comment by acolomb** [comment]
You'll need to give the @weblate user push access to the branch.

**Comment by Catfriend1** [comment]
@acolomb 

I'm stuck adding the bot here:

Screenshot_2024-02-24-13-17-58-788_com android chrome

**Comment by acolomb** [comment]
Looks alright.  Have you checked it's the user for `hosted@weblate.org`?  See https://docs.weblate.org/en/latest/vcs.html:

> The weblate user on GitHub accepts invitations automatically within five minutes.

**Comment by acolomb** [comment]
Well we'd need some new commits on Weblate to really test it.  Best just wait for the next incoming translation change and I'll check if any failure is reported then.

**Comment by Catfriend1** [comment]
@acolomb ok, thank you. Have a nice weekend 🙋‍♂️😊

**Pull request merged**
