### PR TITLE
Fix blocked texts on first welcome page (fixes #835)

### LINKED ISSUE #835: A part of texts could not be seen fully on the first welcome page
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the first welcome page, **A part of texts could not be seen fully**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
103165857-dbaf8580-4857-11eb-9e22-120ae1901389

App version is 1.18.0.0, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts on the first welcome page, and in this circumstance, part of them seem to be blocked. And this page is not scrollable. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app for the first time
3.this error could be seen

**Screenshot**

copy

**Environment**

1. Version of Syncthing-Fork: 1.18.0.0
2. Device : Google Pixel 2,
3. OS version : Android 10.0

### PR DESCRIPTION
**Pull request by yuhuitech**
Dear developer:

I am the creator of issue #835, and I have fixed the blocked texts on the first welcome page. I would appreciate it if you could kindly revise my code and leave me some advice. Thank you so much for your precious time!

Here is the screenshot after my modifications, and I made the text scrollable so I can see all of it.

copy

### CODE REVIEW

**Comment by Catfriend1** [comment]
Thank you very much. Will test it on my phone during next dev session and then give feedback to you.

**Comment by Catfriend1** [comment]
Hi @yuhuitech ,

could you please test the build of this PR using:
- smallest font size
- default font size
-  largest font size 
on your phone and send me some screenshots to review, please?

Thank you.

https://github.com/Catfriend1/syncthing-android/releases/download/v1.18.1.0%2B59b9fd3c/com.github.catfriend1.syncthingandroid_github_v1.18.1.0+59b9fd3c.apk

**Comment by yuhuitech** [comment]
OK, I will work on this :)

**Review by Catfriend1 — APPROVED** [review]

**Comment by Catfriend1** [comment]
It's okay, I made a fast attempt to do this on the emulator. Lgtm. Thank you very much again for contributing to Syncthing Fork :-). You're welcome.

**Pull request merged**
