### PR TITLE
i18n: Lost translations from before Weblate reset

### PR DESCRIPTION
**Pull request by acolomb**
These commits were contained in #1033, but got lost when there were strange internal problems on Weblate.  This should obviously be merged before #1033, as that one contains more recent material.

### CODE REVIEW

**Comment by Catfriend1** [comment]
I'm not sure I did it right... So now we need #1053 and then #1033 ?

**Comment by acolomb** [comment]
Well... No, wrong :-(

I had outlined the easiest order in https://github.com/Catfriend1/syncthing-android/pull/1051 and https://github.com/Catfriend1/syncthing-android/pull/1052#issuecomment-1837156932.  Now let's see how this can be fixed.

**Comment by Catfriend1** [comment]
Should I do revert & re-merge?

**Comment by acolomb** [comment]
> Should I do revert & re-merge?

NO! Please not. Just pushed a commit merging the main branch, without conflicts hopefully.

**Comment by Catfriend1** [comment]
So this is next to be merged?

**Comment by acolomb** [comment]
Yes, please :-)

**Pull request merged**
