### PR TITLE
Add DO_NOT_DELETE file below marker directory  (fixes #131)

### LINKED ISSUE #131: Create .stfolder and DO_NOT_DELETE.txt within it to prevent automatic cleanup of empty directories
Quote from @slashbeast 
 at https://github.com/syncthing/syncthing-android/issues/1249 :
>Some Android distributions, like MIUI, have built-in filesystem cleaner that clean up trash from various locations. Common feature of it is to remove empty directories. I've run into issue where Xiaomi MIUI's Cleaner removed .stfolder rendering syncthing not working. I had to manually add some random, non-empty file there to prevent it from happening again.
It would be nice to have an option in Syncthing for Android to create any non-empty file in .stfolder for the sake of cleaners.

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose
Add "DO_NOT_DELETE" file below marker directory to prevent the syncthing marker folder getting cleaned out for the reason it's an empty folder on Xiaomi MIUI.

Related issues
#131 "[FR] Create dummy, non-empty file in .stfolder to prevent automatic cleanup of empty directories"
https://github.com/syncthing/syncthing-android/issues/1249

Testing
Still needs to be done ...

### CODE REVIEW

**Comment by Catfriend1** [comment]
I somehow feel this might be the wrong place to precreate the file below the marker dir when we're in sendreceive mode. Imagine we create the marker and DO_NOT_DELETE file in a read-only location and syncthing believes the empty folder should scan and propagate its emptyness to the other devices thus deleting all files? Hmm... I need to think through it again and then make the proper fix.

**Comment by Catfriend1** [comment]
This needs to hold until I've finished #135 "Refactor ConfigXml" as just creating a full path-to-folder will be a risk if syncthing core thinks a newly created folder is empty and deletes files from other (write-able) nodes. So I'll do another implementation as I've begun here: I'll check the configXml, get the folder paths before syncthing starts and if the correct path plus ".stfolder" exists, I'll create the file within ".stfolder".

**Comment by Catfriend1** [comment]
@amirulmenjeni Well, not meaning to advertise this, but if you like to try if the fix works on your phone OS (with the system apps / cleaners your manufacturer put on it) feel free to try out Syncthing-Fork.

**Comment by amirulmenjeni** [comment]
@Catfriend1 thanks, will try it out.

**Pull request closed without merging**
