### PR TITLE
Remove pref: Start directly into web gui

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose:
Remove pref: Start directly into web gui

Testing:
Verified working on AVD 9.x at commit https://github.com/Catfriend1/syncthing-android/commit/97fcb709cf3c137f842bf272adc6c3985dad01da .

### CODE REVIEW

**Comment by Catfriend1** [comment]
tx push -s done.

**Comment by phuyuk** [comment]
Why? I can't test this, since no updstes on F-Droid since 1.0.0.5; but I assume this means I won't be able to start directly into the web UI. I prefer the web UI, mostly because it has a dark/black theme - oddly missing in the wrapper.

1) Will the wrapper ever have a dark theme? (assuming that 'starting with web UI' is gone forever)
2) What's going on at F-Droid?!?  Are builds failing?

PS. Any friend of cats is a friend of mine.

**Comment by Catfriend1** [comment]
Hi @phuyuk !

(1) Black theme: I'd wish for someone make a PR or point me to a developer resource or even better an example implementation if I should do that. Myself just hadn't the feeling and time to do this yet as my main concern are the run conditions and planned "AI run conditions" enhancements at the moment.

(2) F-Droid: It recently had some builds failing which worked "by itself" correctly again in the next build session. Currently, it seems to have problems again as I can't reach the live build status page https://f-droid.org/wiki/index.php?title=Special:RecentChanges&limit=250&hidebots=0 - Connection timed out.
 I'm also watching and saw it didn't work for quite some days. When the build log in the wiki was available last time I saw there suddenly were unaccepted Sdk licenses for 28.0.3 logged down. I'm yet unsure if I have to take any action as we built on Sdk 28 before since 2018/09. If the problem persists, I'll reach out to the f-droid team. Soon, we'll switch the build recipe to go 11.4 so that may be a reason for me reaching out after the transition (... in order to have one tickets instead of two, sorry but takes time).

(3) Start to web UI: I understand that you are missing a feature you'd got used to see in the app. Sure, it's just one click away but I see it's hurting you a bit. Which feature from the Web UI are you missing "the most" ? Maybe I can bring this to the wrapper UI? Would you be able to live without the start to web UI feature? If it's too hard and more people complain, I'll surely bring it back. The better way I'm currently thinking about how getting there is I plan to introduce an "expert UI mode" in the near future. So we could make that checkbox visible in expert mode. The reasons for this are mixed - a) Problems with Google's review process for Android TV - b) I don't want to push unexperienced users into the Web UI direction as this had never been implemented "full and clean". It's more hacky because if syncthing web UI triggers a config change this is communicated to the wrapper by the core (in MOST but not ALL circumstances) and the wrapper tries to hot-reload the config. I suspect this also introducing glitches to some users... I'm open for revert if this is the one way to satisfaction, before that, let's see how it does. 

(The rest are thoughts about the new features planned and how they are compatible with all those settings that we already know.)

**Comment by Catfriend1** [comment]
UPDATE: https://forum.f-droid.org/t/whats-the-problem-with-syncthing-fork/4753/6

**Comment by Catfriend1** [comment]
UPDATE: https://gitlab.com/fdroid/fdroidserver/issues/620

**Comment by Catfriend1** [comment]
@phuyuk  New F-Droid release can be found here:
https://github.com/Catfriend1/syncthing-android/releases/tag/v1.0.0.17

**Comment by phuyuk** [comment]
@Catfriend1, thank you so much for giving thoughtful consideration to my concerns - and please accept my apologies for not replying much sooner. Some personal matters have distracted my attention.

I would say that my preference for the web GUI lies mainly in its aesthetic:

1)  Dark Theme. Web GUI has it; wrapper does not.
2)  Page Layout. I much prefer the composition of the web GUI. Lots of useful information, at a glance; efficiently presented in one page.

I fully appreciate that these are somewhat frivolous issues - Syncthing's functionality and reliability are, and should remain, your priorities. But, I would be very grateful for a dark theme... one day.

As for F-Droid, it would behoove them to implement a status page - for its end users. But, enough said about that.

Thanks again for your work. It is appreciated by everyone.

**Comment by Catfriend1** [comment]
@phuyuk 
> Will the wrapper ever have a dark theme? (assuming that 'starting with web UI' is gone forever)
Yes, it's been released today. (Some asset work deferred into the future until I have figured out the best strategy to do this)

**Comment by phuyuk** [comment]
@Catfriend1, this has become my favorite app. I rarely have to interract with it... and I guess that's the point. Thank you very, very much.

**Pull request merged**
