### PR TITLE
 Fix phone plugged to charger detection

### PR DESCRIPTION
**Pull request by Catfriend1**
Testing
Verified working at commit https://github.com/Catfriend1/syncthing-android/pull/27/commits/0a07a6fa95b743ef667559338a4690d60955089c  .

### CODE REVIEW

**Comment by Catfriend1** [comment]
lgtm

**Comment by Catfriend1** [comment]
@chiastic-security @Exist2Resist can you please check the status tab before and after the problem occurs, including some logs? This issue is fixed in my fork at https://github.com/Catfriend1/syncthing-android/releases

**Comment by Exist2Resist** [comment]
@Catfriend1 not sure where I find the status tab, and which logs do you want?

**Comment by Catfriend1** [comment]
The status tab is shown on the right of the folders
...devices..status main screen tab bar. Its only there in this forked version not in the official one. Logs can be gathered via adb logcat from a pc while the phone has usb connection.

**Comment by Exist2Resist** [comment]
I'm not going to install the forked version, don't want to mess around with my settings as I have a workaround for the issue at the moment. 
Here is the logcat, note that there are instances where I trigger the sync manually, usually before bed around 10pm or so and was also doing that this morning at work. 

https://github.com/Exist2Resist/android/blob/master/logcat2.txt

**Comment by Catfriend1** [comment]
Hmm the last event from Android was power disconnected, right? See this line:
 BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.google.android.projection.gearhead/com.google.android.apps.auto.components.connectivity.impl.ConnectivityEventHandlerImpl$ConnectivityEventBroadcastReceiver 09-07 12:58:03.618 6773 6773 V RunConditionMonitor: decideShouldRun: prefRunOnlyWhenCharging && !isCharging 
I'm sure the fork has this fix. Do you charge by usb or wireless pad?

**Comment by Exist2Resist** [comment]
@Catfriend1 no I charge via cable it's a Pixel 2 XL with the latest OS version. 
I'm seeing that all over the place in the logcat.

**Comment by Catfriend1** [comment]
I guess I'd need log referred to by the forked version as too many changes are already in there... Android 8/9?

**Comment by Exist2Resist** [comment]
@Catfriend1 it's Android 9.
I exported the settings from Syncthing, provided they work in the Forked version I'll install it in the next day and restore settings from backup.

**Comment by Catfriend1** [comment]
Its not android compatible atm. I hope I can still help as I dont have lineage 16 yet for my devices.

**Comment by Exist2Resist** [comment]
@Catfriend1 I updated my comment.

**Comment by Catfriend1** [comment]
Okay that came as a surprise. I'm currently making it onto fdroid, so if you like you can get easier updates and be sure the build corresponds to the source.

**Comment by Catfriend1** [comment]
@Exist2Resist You're invited for the experimental version test, if you see fit and like to participate optionally :)
https://github.com/Catfriend1/syncthing-android/issues/44

**Comment by Catfriend1** [comment]
The next fdroid release will have a better support for import and export of settings btw. It can read the settings export from the official version and also export app settings plus the Syncthing config.

**Comment by Exist2Resist** [comment]
@Catfriend1 As of last night I'm running on the Forked version on latest Pie release. 
I can confirm it runs as expected with the run conditions. 
One thing I noticed is you are missing the Send Only toggle in the fork that exists in the Gplay version. 
Not a big deal as I can change that in the WebGUI portion.

**Comment by Catfriend1** [comment]
@Exist2Resist Cool, nice to hear about pie. Thanks for the feedback. The toggle still exists but as a drop down box labeled folder type. It's because I needed three selectable options displayed since we have the receive only folder type upstream.

**Comment by Exist2Resist** [comment]
@Catfriend1 Yup, there it is staring me right in the face. Thanks.

**Pull request merged**
