### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Syncthing/Android app strings (fork)](https://hosted.weblate.org/projects/syncthing/android/catfriend1/fork-stringsxml/).

It also includes following components:

* [Syncthing/Google Play listings (fork)](https://hosted.weblate.org/projects/syncthing/android/catfriend1/fork-play-listings/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Catfriend1** [comment]
@acolomb 

In which intervals would you recommend to merge this? Squash merge okay?

**Comment by acolomb** [comment]
Actually not sure.  I'm just right now trying to fix whatever broke after merging the Weblate PR in the upstream repo.

**Comment by Catfriend1** [comment]
@acolomb Where do those german translation changes come from? Might be that I'm too much of a creature of habit, but I would prefer to keep the German translation "as it is". I also remember that I did some "fine tuning" years ago - even if it did not exactly match the english to german translation people might expect - and honestly, got used to it as I use the app daily in my native language.

Here is an example where I don't know why "sleeping" is "deaktiviert" in the end... can we change such and similar cases back to get a "smaller PR"?

image

**Comment by acolomb** [comment]
Well that's the deal with sharing translations between forks.  I see that as a major benefit of the Weblate integration.  If you want to argue about individual strings, that's best done directly on Weblate, with the other users active in the translation.  In this case it's been "Masowick" making the changes, and that person is quite responsive and open to discussion.

I'd say the advantage of getting improvements to translations from the upstream app outweighs the disadvantage of losing control over a single language.  You can always change the string IDs to stop the automatic propagation, but I surely wouldn't recommend it.

**Comment by acolomb** [comment]
> Here is an example where I don't know why "sleeping" is "deaktiviert" in the end... can we change such and similar cases back to get a "smaller PR", please?

For this issue at hand, see the explanation here: https://hosted.weblate.org/translate/syncthing/android/stringsxml/de/?checksum=402f744a59e82f73#comments

**Comment by Catfriend1** [comment]
Ok, understood. I'll sleep some nights "about" it and then decide.
Basically there are two ideas:
- Bite the apple and let the community do german as everyone pleases.
- Preserve the love that I first went to Transifex, updated (new) german id's and then baked a new release, which I could now do directly within the xml.

Maybe it's not as drama as I thought on first sighting... the Syncthing is "disabled" was the biggest shoutout I remember on the app back in 2018/2019 because of failing run conditions, it made users angry. We now have the status tab, so should be finde whatever it says. The other thing is: I am very keen on keeping some strings short (even if inaccurate to the original english wording) so the screen fits without any (time consuming) layout changes etc.

**Comment by acolomb** [comment]
You can always go to Weblate and suggest an improvement, which will benefit both apps hopefully.  Limited screen space is also a concern for the upstream app, so your efforts will be welcomed there instead of just living in the fork.

**Comment by Catfriend1** [comment]
Okay, that's welcome. Just give me some time. I still to take a calm moment to learn Weblate and what is where to participate in there correctly.

**Comment by acolomb** [comment]
It would help to get this PR merged from time to time, not waiting until the last moment before a release.  Makes it easier to base new work on it, without causing conflicts repeatedly.  That's why Weblate calls it "Continuous Localization"...

**Comment by acolomb** [comment]
@Catfriend1 there was some breakage on Weblate unfortunately.  Their support trying to fix a bug actually reset the translations partly.  I'll need to investigate what the currently correct state is...

**Comment by acolomb** [comment]
@Catfriend1 the breakage should be fixed on Weblate's side.  I've created #1053 to recover what was lost during the repair.

I'd actually be happy to get these PRs merged soon. I don't think you'll be able to judge all languages' translation changes?  And just in case, there is always full Git history available to see what's changed in a specific language.

Note that in a situation like this, every day of waiting brings more potential for conflicts, because the translations are a moving target with people making changes whenever they find the time.

**Comment by Catfriend1** [comment]
Ok, I'll try to do the next dev session asap :)

**Comment by Catfriend1** [comment]
Ok, after this I'll try to compile it and see what lint says.

**Comment by acolomb** [comment]
#1054 replaces this one.  That's the only way I can correct the merge conflicts on Weblate without direct push access.

**Comment by Catfriend1** [comment]
Ok, thanks for your work. I think we can c
close this .

**Comment by acolomb** [comment]
Yes, please close. I think Weblate is happy again.

**Pull request closed without merging**
