### PR TITLE
Optimize onboarding screen to fit on screens and improve texts (fixes #126) (fixes #192)

### LINKED ISSUE #126: Onboarding screen doesn't look well in smaller screens
### Description of the issue
The onboarding screen is a nice thing to have which is missing in the official android app. It could be made a little more better on smaller screens. The following is how it looks on a 4.3" screen:

screenshot_2018-11-17-00-47-37

### Reproducer
1. If already installed, clear the data of the app or re-install the app.
2. Open the app

### Version Information
    App Version: 0.14.51.13
    Syncthing Version: 0.14.51.13
    Android Version: Android 5.1.1

### LINKED ISSUE #192: Syncthing-Fork v1.0.0.1 fails to open "Disable Battery Optimization" on Shield TV
If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue
Syncthing-Fork v1.0.0.1 fails to open "Disable Battery Optimization" on nVidia Shield Android TV with Android 8.0.0, Experience Update v7.2.1.

Here's a [YouTube video](https://www.youtube.com/watch?v=4BMiW_REBfs) showing the very issue.

I've mentioned the issue for sniper at [nVidia GefForce forums](https://forums.geforce.com/default/board/159/), he says there's been no recent code changes related to that popup/ dialog in Shield TV firmware. Might never functioned properly ever since Shield got updated to Oreo, but I don't know that.

### Reproducer
* Install Syncthing-Fork on nVidia Shield Android TV running Shield Experience Update 7.2.1.
* Go through the initialization wizard. You won't get past the step regarding disabling Android battery optimization for Syncthing-Fork. Syncthing official android wrapper also fails here.

### Version Information
    App Version: 1.0.0.1
    Syncthing Version: 1.0.0.0
    Android Version: Android 8.0.0, Shield Experience Update 7.2.1

### Android Log
    adb shell / logcat
    or MatLog (search on GitHub) output
*MatLog won't run on Android TV*

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose:
Optimize onboarding screen to fit on smaller screens and improve texts

Related issue:
#126 - Onboarding screen doesn't look well in smaller screens
#192 - Syncthing-Fork v1.0.0.1 fails to open "Disable Battery Optimization" on Shield TV

Screenshots:
image

Testing:
Verified working at commit https://github.com/Catfriend1/syncthing-android/commit/8eb912065cb3a312e8478292576d5358bdf6446e with different phones, see below.

### CODE REVIEW

**Comment by Catfriend1** [comment]
WAIT: Finish #195 before merge.

**Comment by Catfriend1** [comment]
Hey @o-l-a-v ,
would you mind helping me on this? Some users repored the welcome slides on first app launch look terrible on older phones with a smaller display. So I've optimized them to fit. I have sort of a problem or let's say a bad feeling after I tested this on some phones in portrait and landscape mode that it may not be "readable" on a TV.
If you'd have some time for this, I'd appreciate your help very much.

The test APK can be found here: https://drive.google.com/open?id=1asRf-odl1whXeTAdbILy9CDIiO1k-hHn

Thank you.

**Comment by o-l-a-v** [comment]
The text is small, but readable. Is it possible to scale/ set font size based on DPI or something?
img_20190105_112456
img_20190105_112425

**Comment by Catfriend1** [comment]
> Is it possible to scale/ set font size based on DPI or something?
Unforunately I haven't figured this out yet. I think the "dimens" file could help here as there are dpi-dependent sizes defined. Not sure how to implement this correctly. I'm currently setting up a TV virtual device.

**Comment by Catfriend1** [comment]
Ok, I added a second size definition for TV's.
image

**Comment by Catfriend1** [comment]
@o-l-a-v It now looks like this, do you agree?
image

**Comment by Catfriend1** [comment]
Verified everything is working correctly at commit https://github.com/Catfriend1/syncthing-android/commit/8eb912065cb3a312e8478292576d5358bdf6446e with different phones. (Nexus One, Nexus 4, Pixel 2, Android TV AVD)

**Comment by Catfriend1** [comment]
Ran lint on variant debug: 0 issues found
Ran lint on variant release: 0 issues found
> lgtm!

**Pull request merged**
