### PR TITLE
Schedule a backup stop job when running on schedule (fixes #803)

### LINKED ISSUE #803: Sometimes doesn't stop after 5 minutes despite "Run according to time schedule" ticked
I have "Run according to time schedule" ticked and usually it works, but sometimes I notice that the notification is still showing for several hours or even days, and that the "uptime" is showing this too. Doing Force Stop then Follow Run Conditions seems to temporarily fix.

### PR DESCRIPTION
**Pull request by Helium314**
As written in https://github.com/Catfriend1/syncthing-android/issues/803#issuecomment-859809935, this should fix the suspected cause of #803. I never had this bug, so I can't check whether it really helps.

I did not test the changed code, but it looks simple enough to be confident it will run correctly.

### CODE REVIEW

**Comment by Catfriend1** [comment]
Thank you very much for caring. So, to verify the change I'd suggest making a debug APK and handing it out for feedback to the people complaining in the linked issue, right?

**Comment by Catfriend1** [comment]
Link to debug APK: https://github.com/Catfriend1/syncthing-android/releases/download/v1.18.1.0%2B59b9fd3c/com.github.catfriend1.syncthingandroid_github_v1.18.1.0+59b9fd3c.apk

**Comment by Catfriend1** [comment]
@Helium314  Does the debug APK (see above) work correctly with the fix?

**Comment by Helium314** [comment]
I didn't try the APK as I never had this bug, and I guess it might be too early to say whether this PR fixes it.
So far there was no feedback on the test version, but maybe it's just too early.

**Comment by Helium314** [comment]
I just added another commit:
if syncthing is running (lastDeterminedShouldRun = true), never schedule 1 hour jobs: should get out of the bad condition sooner, but doesn't avoid it completely

(forget the other change, I still had it in there from my previous attempt and will revert it)

**Comment by Helium314** [comment]
Ok, I had some time and decided to try changing `SyncTriggerReceiver` a bit:
So far it would toggle the state whenever it would receive something. With my PR #766 the behavior got less robust when Android is messing with the schedule.

So now an `ACTION_SYNC_TRIGGER_FIRED` intent _without_ `EXTRA_BEGIN_ACTIVE_TIME_WINDOW` will stop Syncthing (if it's running on schedule), and an intent _with_ `EXTRA_BEGIN_ACTIVE_TIME_WINDOW` will start Syncthing.
This means that a delayed stop job will definitely stop Syncthing and hopefully #803 will be fixed.

I did not yet test whether this really works (or whether is has unexpected side effects)

**Comment by Catfriend1** [comment]
Good work @Helium314 . I did not test it , btw. Let's hope , we don't need to revive WAKE_LOCKS ( https://stackoverflow.com/a/67113218 ) in the end. My Android 11 phone has problems allowing network traffic while on battery and the screen is off - no matter which extra permissions I assign from Android settings.

**Comment by Helium314** [comment]
Could you do a build for me?
When trying to test, I noticed I forgot to build the syncthing library, and I don't really want to install/setup Go again just for one test...

>  Let's hope , we don't need to revive WAKE_LOCKS ( https://stackoverflow.com/a/67113218 ) in the end. My Android 11 phone has problems allowing network traffic while on battery and the screen is off - no matter which extra permissions I assign from Android settings.

I also noticed that sometimes syncthing is running, but not or very slowly syncing when the phone is in sleep mode (screen off, no music playing and not plugged). Even with all available power saving settings disabled this happens...
But acquiring a wake lock might be too much, especially if syncthing has nothing to do anyway (which for me is the case in ~90% of the 5 min runs).

**Comment by Catfriend1** [comment]
> I also noticed that sometimes syncthing is running, but not or very slowly syncing when the phone is in sleep mode (screen off, no music playing and not plugged). Even with all available power saving settings disabled this happens...

Exactly my observation ;-). even allowing unrestricted background data it doesn't get better.

**Comment by Catfriend1** [comment]
@Helium314  You're also allowed to post e.g. gdrive links for your test apk so users can join the test.

**Comment by Helium314** [comment]
have a look here: https://github.com/Helium314/syncthing-android/releases/tag/v1.18
The pagckage is renamed with a _2_ at the end to allow install parallel to Syncthing-Fork

**Comment by Catfriend1** [comment]
@JohnVeness Could you please test Helium314's debug APK?

**Comment by JohnVeness** [comment]
Thanks. I have just installed and will report back

**Comment by JohnVeness** [comment]
I have been running the test APK for the last seven days with no observed problems - I have not once seen a sync run over 5 minutes, so the fix seems to work for me. Thanks.

**Comment by Catfriend1** [comment]
@Helium314 Whats your opinion on this? Should we merge or wait for more users to test?

**Comment by Helium314** [comment]
@JohnVeness said in https://github.com/Catfriend1/syncthing-android/issues/803#issuecomment-912753413 that my first attempted fix was fine initially, but things got worse after several days.

So maybe we should wait for a few more days, just to be sure.

**Comment by Helium314** [comment]
Ok, it's been 3 more days and @JohnVeness didn't report any problems. So it looks like the problem is really solved and PR could be merged.

**Review by Catfriend1 — APPROVED** [review]

**Comment by Catfriend1** [comment]
Thanks @Helium314 for your hard work on this until you finally found the right fix :-) 🚀  👍

**Comment by Catfriend1** [comment]
Thanks @JohnVeness for helping @Helium314  with the testing of this PR. Very kind of you!

**Comment by JohnVeness** [comment]
No worries, glad to help! The fix has been rock solid for ten days :blush:

**Pull request merged**
