### PR TITLE
possible fix for 'Could not determine app's private files directory'

### PR DESCRIPTION
**Pull request by balihb**
#759 
the possible fix I proposed for the issue. this solution won't remove the first element from the list, but instead choose the 2nd one if there is more than one.

### CODE REVIEW

**Comment by balihb** [comment]
@Catfriend1 is it possible to maybe puss this change to the Play Store beta, so I can test if it works? Or how should we step forward?

**Comment by Catfriend1** [comment]
Hi,

I'm a little bit busy and behind atm, ir it's just testing you can use the compile scripts from this repo to make your own debut build easily without signing stuff or I could do an APK build for you.

**Comment by Catfriend1** [comment]
Memo for me: Look up why we changed the path detection in the past (remember crashes? issues with phone manufacturer stock os'es?) There was a ticket, not that we reintroduce the probleme again for others.

**Comment by Catfriend1** [comment]
Ah yes , I should do something here when time allows, still noted!

**Review by Catfriend1 — APPROVED** [review]

**Comment by Catfriend1** [comment]
Merged into "beta" branch.

**Comment by Catfriend1** [comment]
AVD 11:
image

**Comment by Catfriend1** [comment]
Problem: After this PR it does not save the emergency export to internal storage.

INTERNAL STORAGE:
image

EXTERNAL SD CARD STORAGE:
image

**Review by Catfriend1 — CHANGES_REQUESTED** [review]
.

**Comment by Catfriend1** [comment]
@balihb  Something maybe is wrong what I've stated above. Let's do a test build ( https://drive.google.com/file/d/1FVLHSkIamwFNrhQGOLBj2qNz8Jnqh2KV/view?usp=sharing ) . Could you please check if this build fixes the problem on your phone you've originally had?

**Comment by balihb** [comment]
> @balihb Something maybe is wrong what I've stated above. Let's do a test build ( https://drive.google.com/file/d/1FVLHSkIamwFNrhQGOLBj2qNz8Jnqh2KV/view?usp=sharing ) . Could you please check if this build fixes the problem on your phone you've originally had?

with this I could grant all file access, but I didn't and I pressed the emergency button. gave me the same failure.

**Comment by balihb** [comment]
Failed to export config
java.io.FileNotFoundException: /data/user/0/com.github.catfriend1.syncthingandroid.debug/files/config.xml: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:130)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:120)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:264)
	at com.google.common.io.Files.copy(Files.java:326)
	at com.nutomic.syncthingandroid.activities.FirstStartActivity.exportConfig(FirstStartActivity.java:778)
	at com.nutomic.syncthingandroid.activities.FirstStartActivity.access$400(FirstStartActivity.java:54)
	at com.nutomic.syncthingandroid.activities.FirstStartActivity$ViewPagerAdapter$1.onClick(FirstStartActivity.java:410)
	at android.view.View.performClick(View.java:7496)
	at android.view.View.performClickInternal(View.java:7473)
	at android.view.View.access$3600(View.java:831)
	at android.view.View$PerformClick.run(View.java:28641)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7762)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 19 more

**Comment by Catfriend1** [comment]
@balihb Did you configure Syncthing first before revoking all files permission and trying the emergency export?

**Comment by Catfriend1** [comment]
We should maybe add the extra code which displays an error more clear if Syncthing has nothing to export when it was'nt configured.

**Comment by Catfriend1** [comment]
I'm closing this. Later to be re-opened, when we know what needs exactly to be fixed and how.

**Comment by Catfriend1** [comment]
Bug on some devices: https://github.com/Catfriend1/syncthing-android/issues/541

**Pull request closed without merging**
