### PR TITLE
Allow specifying different sync conditions per folder (fixes #57)

### LINKED ISSUE #57: [FR] Feature Request: Different synchronisation conditions per folder
Quote from @cdrfun at https://github.com/syncthing/syncthing-android/issues/1225
> Hi there, it would be great if you could define different synchronisation conditions per folder.
Possible use case:
One folder which is important should always be up to date - no matter if I'm on WiFi or battery. For me this would be my folder with the password manager database.
Other folders like photos could be synched only with WiFi and/or battery.
Would this be possible given the current architecture?
What do you think about this idea, aside from technicalities.
Greetings!

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose
Provide the ability to specify different sync conditions for each syncthing folder through the wrapper UI.
Available conditions per folder:
- Sync on WiFi
- Sync on specified WiFi
- Sync on metered WiFi
- Sync on mobile data

Screenshots

Related issue:
#57 "[FR] Feature Request: Different synchronization conditions per folder"

Related bounty
https://www.bountysource.com/issues/28940393-enhancement-request-per-folder-sync-only-when-charging-on-wifi

Testing
Verified working at commit https://github.com/Catfriend1/syncthing-android/pull/66/commits/5f005c523b5442b70f36eff3e2b4e98cc15c71eb on:
- AVD Android 9.x
- Xiaomi Mi8 running MIUI 10, Android 8.1.0

### CODE REVIEW

**Comment by Catfriend1** [comment]
@Review/Complete.
lgtm.

**Comment by Catfriend1** [comment]
@oneyb 
The feature you requested in https://github.com/syncthing/syncthing-android/issues/1186 is now implemented in Syncthing-Fork.

**Comment by Catfriend1** [comment]
@JohnCardenas @sim6 @amette @Flowdalic @hvhaugwitz @edgimar @robert7k @Aq32 @mrbrahman
The feature you requested in syncthing#511 is now implemented in Syncthing-Fork.

**Comment by Catfriend1** [comment]
@karlicoss  This is already released with Syncthing-Fork. Bounty's welcome :)

**Comment by karlicoss** [comment]
@Catfriend1 awesome, didn't realize this fork existed. Just seamlessly switched from the original app so thanks :)
One small question -- if I want to keep folders A, B and C synced on wifi and folder D on mobile network as well -- is the quickest way enabling mobile sync globally and adjusting per-folder sync for A, B and C to disable mobile sync? If I do it the other way around, that is, disable mobile sync globally, and try to enable it for D only, it doesn't work as mobile sync seems to be grayed out in D sync settings.
Another GUI suggestion: might be nice to display sync settings summary perhaps as small icons in 'Folders' tab. But that's a really minor thing so probably only worth for someone really keen on polishing the UI to implement.

**Comment by Catfriend1** [comment]
@karlicoss 
> is the quickest way enabling mobile sync globally and adjusting per-folder sync for A, B and C to disable mobile sync?

Yes. I intend to improve this by "whitelist-thinking" in issue https://github.com/Catfriend1/syncthing-android/issues/110 but currently I'm focusing on other improvements. This "positive way of thinking what a user enables" instead of the "negative" disabling would be easier but turned out to be a lot of work on the code and requiring intensive testing before release.

**Pull request merged**
