### PR TITLE
completed strings for pt-br

### PR DESCRIPTION
**Pull request by inkhorn-ptbr**

### CODE REVIEW

**Comment by inkhorn-ptbr** [comment]
Hello dev, it was much easier to do it through PR, if you can please upload those strings manually, if it's necessary, thanks

**Comment by Catfriend1** [comment]
sry no, transifex is very easy. anyway thanks.

**Comment by inkhorn-ptbr** [comment]
well, what can I say to that

**Comment by Catfriend1** [comment]
It's a matter of time ... this would cost me a LOT of extra time if the projects' default process of translating via Transifex is not followed. Plus, you won't have a reviewer - like some people are already set up to review that language translations on Transifex. I cannot review myself because I don't know the language.
Sorry.

**Pull request closed without merging**
