### PR TITLE
Workaround cleanup of the folder marker by Huawei, Xiaomi firmware (fixes #131)

### LINKED ISSUE #131: Create .stfolder and DO_NOT_DELETE.txt within it to prevent automatic cleanup of empty directories
Quote from @slashbeast 
 at https://github.com/syncthing/syncthing-android/issues/1249 :
>Some Android distributions, like MIUI, have built-in filesystem cleaner that clean up trash from various locations. Common feature of it is to remove empty directories. I've run into issue where Xiaomi MIUI's Cleaner removed .stfolder rendering syncthing not working. I had to manually add some random, non-empty file there to prevent it from happening again.
It would be nice to have an option in Syncthing for Android to create any non-empty file in .stfolder for the sake of cleaners.

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose:
- Create .stfolder and DO_NOT_DELETE.txt within it to prevent automatic cleanup of empty directories (fixes #131)
- This is a workaround for phones running manufacturer specific cleanup tools in the background.

Testing:
- Verified doing technically the right thing on AVD 9.x at commit https://github.com/Catfriend1/syncthing-android/pull/363/commits/99e1659926ba6fc6ad5215d263424bdc107a8f4d .
- Needs community test.

### CODE REVIEW

**Comment by Catfriend1** [comment]
@Review/Complete
lgtm.

**Comment by Catfriend1** [comment]
Anyone having the same issue reading this? I've put up a test APK at https://drive.google.com/open?id=1FyPl16VXL6WAjuazSDIBtaN79ZRCTX0o and would appreciate feedback if this works correctly after adding a new folder and running the phone's file cleanup utility. The workaround adds a dummy text file below the ".stfolder" directory.

**Comment by otbutz** [comment]
@Catfriend1 i don't have a phone which is affected but it might be worth to run a public beta test on the PlayStore for things like this

**Comment by GottZ** [comment]
what about already existing sync folders where the .stfolder has been deleted already?
i doubt users know what to do when they see the "folder marker missing" error.

**Comment by GottZ** [comment]
hereby confirm this works on my Huawei Mate 10 Pro

**Comment by Catfriend1** [comment]
Thanks for reporting back. Already missing markers have to be restored manually as it would circumvent the safety meaning of why the marker exists when we would recreate it automatically.

**Pull request merged**
