### PR TITLE
Document how to switch from official version

### PR DESCRIPTION
**Pull request by erikvanoosten**
Based on the documentation in https://github.com/Catfriend1/syncthing-android/issues/1141#issuecomment-2395393953

### CODE REVIEW

**Comment by Catfriend1** [comment]
Wow, thanks.

> Like magic, everything should be as it was in Syncthing-fork


... Official in the end?

**Comment by erikvanoosten** [comment]
Yeah, that's right. I did a straight copy from the comment and didn't notice ☺️

**Comment by erikvanoosten** [comment]
Thanks! I am in transit so it would have taken some time to do it myself.

**Comment by Hob111** [comment]
It seems my request for information, #1141. was unintentionally very apposite. 
May I take this opportunity to thank @Catfriend1 for all the time and effort he puts into this (no longer) fork. I'd be lost without Syncthing on my Android devices.

**Pull request merged**
