### PR TITLE
Add support for WiFi-Direct connections (fixes #423)

### LINKED ISSUE #423: Implement WiFi Direct for direct connection
Yeah, this would be cool. Especially if you meet a stranger and just need a one-time WiFi connection to use Syncthing, e.g. to share some pics.

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose:
- Add support for WiFi-Direct connections (fixes #423)

### CODE REVIEW

**Comment by Catfriend1** [comment]
Yeeeha, it works! :-) :-) :-)
image

**Comment by Catfriend1** [comment]
Ping @mehrdadn @grimpy @toddnni @edrex @DrSchnagels @daviewales 

Hey folks,

would you like to help me trying this out when it reaches BETA status? I could really need more testers and devices out there. This Wifi-Direct stuff doesn't work on the Android emulator.

Kind regards
Catfriend1

Refs.:
https://github.com/syncthing/syncthing-android/issues/1308
https://github.com/syncthing/syncthing-android/issues/1034
https://github.com/syncthing/syncthing-android/issues/641
https://github.com/syncthing/syncthing-android/issues/1308
https://github.com/syncthing/syncthing-android/pull/341
https://github.com/syncthing/syncthing-android/issues/194

**Comment by mehrdadn** [comment]
Is this only Wi-Fi Direct or would it work for Wi-Fi Hotspot too? I don't really know anything about Wi-Fi Direct (I never use it)—but the initial thread was about turning on Wi-Fi Hotspot, connecting to the phone that way, and using that to sync.

**Comment by Catfriend1** [comment]
It's only direct because it's easier to handle than hotspot. You won't need a password on connect but the approval on the other side. Hotspot has disadvantages like that syncthing may use the other side's internet connection accidentally and wifi direct only generates a local network without internet access

**Comment by mehrdadn** [comment]
Yeah I don't use Direct, sorry...

**Comment by daviewales** [comment]
As far as I can tell, Macs don't support Wi-Fi direct. So I won't be able to test this.

Regarding hotspot mode, couldn't Syncthing choose to only make connections in the local IP range?

**Comment by mehrdadn** [comment]
It could and should try to do that. There's really no reason it shouldn't be working.

**Comment by Catfriend1** [comment]
I don't have a Mac, probably you are more informed about this than me just reading https://babaawesam.com/2013/07/09/fast-transfer-from-android-to-macbook-wirelessly/ ...!
In the first step of development, I'm introducing an easy pairing mode between Android devices using Wifi-direct. If this works okay, maybe we'll also add hotspot later.

For the moment Hotspot can be used with the app, but needs some caring of the user. For example if you'd like to avoid sharing your internet connection with another syncthing instance, you could put the phone into Airplane mode, host the Hostspot, edit the run conditions (Run when phone has no internet connection) and then connect your second phone/mac or whatever to that hotspot. This is what already works.

**Comment by Catfriend1** [comment]
So concept will be:
- WiFi direct can be enabled in a new tab called "WiDi".
- This tab - when enabled - shows nearby devices and their Syncthing IDs.
- The user chooses which IDs to authorize.
- The app takes care of the WiDi connection establishment and pairing of the two devices if the Syncthing ID isn't present in config.xml (configured / ignored devices) yet.

**Comment by mehrdadn** [comment]
> For example if you'd like to avoid sharing your internet connection

> you could put the phone into Airplane mode

This would accomplish exactly the opposite of what what was intended. The idea was to be able to directly use Syncthing over Hotspot (which uses 192.168.43/24), while the laptop is also using Hotspot to connect to the internet. Either way there is absolutely no reason for the existence or lack of an internet connection and/or airplane to have any relevance at all. It shouldn't matter.

**Comment by Catfriend1** [comment]
Well every user might have another requirement and one syncs over wan and one prefers local networks lan+wifi only. You're right it shouldn't matter and also no one should be pissed of a burnt through mobile data plan, that's why wifi direct is the current goal.

**Comment by mehrdadn** [comment]
I'm confused why you tagged me and [my post](/syncthing/syncthing-android/issues/1308) then, when you're trying to accomplish the exact opposite of the goal I outlined in that post...

**Pull request closed without merging**
