### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Syncthing/Android app strings (fork)](https://hosted.weblate.org/projects/syncthing/android/catfriend1/fork-stringsxml/).

It also includes following components:

* [Syncthing/Google Play listings (fork)](https://hosted.weblate.org/projects/syncthing/android/catfriend1/fork-play-listings/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Catfriend1** [comment]
@acolomb should we go for this as well before I test compile?

**Comment by acolomb** [comment]
AFAICT there were never any strings related to `notification_type_*` in `app/src/res/values/strings.xml`, the English source language file.

Did you ever add them?

**Comment by acolomb** [comment]
Ah, got it.  That's something that got added upstream, and I carried it over as part of the `string-array` replacement.  But the fork seems to miss that functionality.

Should we remove the definitions from `arrays.xml`? Or do you want to pull in the respective changes from upstream?

**Comment by Catfriend1** [comment]
@acolomb  Ah I see, so it can be commented out? I'll try and check compilation.

**Comment by Catfriend1** [comment]
Now it compiles well with the one array related to notifications commented out. 

image

Can I leave it like that?

**Comment by acolomb** [comment]
I have little knowledge about Android app development, so not sure about the Gradle warnings.  But I've seem them on the upstream build as well, and it didn't hurt there.  So, from my side it looks OK.

**Comment by acolomb** [comment]
One more thing, I guess you haven't set up a Webhook for Weblate to pick up upstream changes immediately?  That would be great to speed up propagation of new strings. See here:

https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

**Comment by Catfriend1** [comment]
@acolomb Can I do this webhook thingy alone? Or would it be better we meet up in Discord and do this together?

**Comment by acolomb** [comment]
Hm... I think you can manage it according to the linked instructions.  If not, sure we can connect up somehow.  TeamViewer, Discord, whatever.  I have a Discord account somewhere, but not actively using it.

**Comment by Catfriend1** [comment]
What is the correct URL, docs state: https://hosted.weblate.org/hooks/github/ but the text says I need the weblate URL somehow.
If I enter https://hosted.weblate.org/projects/syncthing/android/catfriend1/hooks/github/ it is 404.

**Comment by Catfriend1** [comment]
I've added it now, without a secret. Not sure if this will work on the other side:
image

**Comment by acolomb** [comment]
Looks good I guess.  The `https://hosted.weblate.org/hooks/github/` URL is correct, ast he note in the docs says.  Weblate is a system which you can self-host, in which case you need to construct your own URL.  But for *Hosted* Weblate, it's just the one listed in the docs.

**Comment by Catfriend1** [comment]
How can we test communication on weblate side?

**Comment by acolomb** [comment]
When you push a commit, it will trigger an update on Weblate automatically.  You should see an entry in https://hosted.weblate.org/projects/syncthing/android/catfriend1/fork-stringsxml/#history

**Comment by Catfriend1** [comment]
Ok, I'll change a string for testing and then back? Or does this wipe existing translations like Transifex did before so I'd better not do that test and check back next time?

**Comment by Catfriend1** [comment]
@acolomb  Ok, thanks for the explanation. I'll try with a new string in https://github.com/Catfriend1/syncthing-android/pull/1058

**Comment by Catfriend1** [comment]
@acolomb  Cool, it worked :-).

image

**Comment by Catfriend1** [comment]
@acolomb  Is there a button "make new PR with updated translations now"?

**Comment by acolomb** [comment]
Yes, there is, but only for project admins on Weblate.  Let me see if I can assign that permission to you.

**Comment by acolomb** [comment]
You should have access to this now: https://hosted.weblate.org/projects/syncthing/android/catfriend1/fork-stringsxml/#repository

**Pull request merged**
