### PR TITLE
Fix service.startForeground on Android 8+ (fixes #18) (fixes #80)

### LINKED ISSUE #18: Context.startForegroundService() did not then call Service.startForeground()
Quote from @ Catfriend1 https://github.com/syncthing/syncthing-android/issues/1192

> From GPlay Console
image

> Impact
Android 8+ users cannot run syncthing as a background service without getting a hang if the service startup takes longer than 5 seconds. This is due to a recently introduced android restriction. There were also some users leaving feedback on google play related to this problem that "Syncthing would hang a lot on Android 8+".

Quote from https://stackoverflow.com/a/45047542
>From Google's docs on Android 8.0 behavior changes:

The system allows apps to call Context.startForegroundService() even while the app is in the background. However, the app must call that service's startForeground() method within five seconds after the service is created.
Solution: Call startForeground in Oncreate() for the Service which you use Context.startForegroundService().
https://developer.android.com/about/versions/oreo/android-8.0-changes.html
https://developer.android.com/about/versions/oreo/background.html

### LINKED ISSUE #80: startActivity called from non-Activity context
### Reproducer
1. Start syncthing app.
2. Go to home screen.
3. Click the notification to get into MainActivity again.

### Version Information
    App Version: 0.14.51.3
    Syncthing Version: v0.14.51
    Android Version: Android 8.1.0 MIUI 10

### Android Log
    adb shell / logcat
    or MatLog (search on GitHub) output

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose 1
Add push APK to device after build script

Purpose 2
Fix issue #18 "Context.startForegroundService() did not then call Service.startForeground()"

Purpose 3
Fix issue #80 "startActivity called from non-Activity context"

Testing
Verified working at https://github.com/Catfriend1/syncthing-android/pull/79/commits/776b87927e656ae913068e3195eff00c235783af 
- Android 7.1.2 (lg-h815)
- Android 8.1.0 (MIUI 10 Xiami Mi8)

### CODE REVIEW

**Comment by Catfriend1** [comment]
@Review/Complete.
lgtm.

**Comment by Catfriend1** [comment]
@dovydasvenckus  Would you mind testing syncthing fork and give me feedback if starting from intent works correctly? See https://github.com/Catfriend1/syncthing-android/releases

**Comment by dovydasvenckus** [comment]
Sure. I'll test it today later in evening or tomorrow.

**Comment by dovydasvenckus** [comment]
Yep it seems to run fine in background :).
I hope it will be merged in main project.
Thanks man :+1:

**Comment by Catfriend1** [comment]
Thanks for reporting back :)

**Pull request merged**
