### PR TITLE
Per-Folder/Device sync conditon: power source (fixes #666)

### LINKED ISSUE #666: Per-Folder Custom Sync Conditions: Power (AC-only)

### PR DESCRIPTION
**Pull request by Helium314**
This adds _power source_ to custom sync conditions, like it already exists in global settings.
Choice is only available if the global setting is to run on AC and battery.

I don't have much experience in Android coding, so please forgive beginner's mistakes.

There should be an icon added to be consistent with the other sync conditions, but I don't have any knowledge in how to work with SVGs. Help is very welcome.
Meanwhile `ic_signal_wifi_0_bar_black_24dp` is a placeholder.

### CODE REVIEW

**Comment by Catfriend1** [comment]
Hi,

thanks for the code :-). I'll take a closer look during my next dev session. One question ahead: Did you compile it and use it on your phone? Would be nice if we could at last agree on sth like "worked on your phone/syncthing environment fine for 14 days" and then have some screenshots herein.

**Comment by Helium314** [comment]
It works on my phone, but so far it's been running only for a few hours.

**Comment by Catfriend1** [comment]
Keep on testing please 👍

**Comment by Helium314** [comment]
Here everything is working as expected so far.

Since you wanted a screenshot:
Syncthing-Fork

Two cosmetic issues:
* still needs its own icon. I don't know how to do this properly. Simply using ic_batter_lightning was a bad idea, it is too large and always white.
* text is too small. It looks good if I add `android:textSize="15sp"`, but since nowhere in the .xml text size is specified explicitely I have doubts whether doing this is a good fix.

Then two more things:
* I set `private static final String POWER_SOURCE_CHARGER_BATTERY = "ac_and_battery_power";` to `public` so I can access it from SyncConditionsActivity. Is this ok? It looks strange with the other 2 POWER_SOURCE strings being private...
* `checkObjectSyncConditions` uses code copied from `decideShouldRun`. This should maybe move into a separate `SyncConditionResult checkConditionSyncOnPower` to have it only once?

**Comment by Catfriend1** [comment]
Perfect, if nothing comes in my way, we head to merge/test release next week

**Comment by Catfriend1** [comment]
> checkObjectSyncConditions uses code copied from decideShouldRun. This should maybe move into a separate SyncConditionResult checkConditionSyncOnPower to have it only once?

This would be nice if you could avoid code duplication.

**Comment by Catfriend1** [comment]
Top :-)

**Comment by Catfriend1** [comment]
How is your next step planned on this? Are you trying to make up an icon (or copy one from the material io docs, see other PR) so I still need to wait for a new commit?

**Comment by Helium314** [comment]
I am still not sure whether it's ok to simply add `android:textSize="15sp` for the 'Run when device is powered by' part.
As for the icon, I'll try adjusting `ic_batter_lightning` to have the right size and add an inverted version.

But currently I'm working on getting better icons for the QS tiles

**Comment by Catfriend1** [comment]
In my opinion feel free to add the size attribute. If I find sth better I'll edit it later after merging when doing the "gradlew lint" which sometimes gives advice.

**Comment by Helium314** [comment]
Text size is changed, adjusted battery icon added.
I think this is ready.

**Review by Catfriend1 — APPROVED** [review]

**Comment by Catfriend1** [comment]
Merged into "beta" branch.

**Review by Catfriend1 — APPROVED** [review]

**Review by Catfriend1 — APPROVED** [review]

**Comment by Catfriend1** [comment]
Thanks for this great improvement via your contribution ! :-)

**Pull request merged**
