### PR TITLE
Status tab - add button to "force start" / "force stop" (fixes #394)

### LINKED ISSUE #394: Status tab - add button to "force start" / "force stop"
Run conditions - Button "Sync now for 5 minutes"

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose:
- Status tab - add button to "force start" / "force stop" (fixes #394)

Issues:
- Status tab - add button to "force start" / "force stop" (fixes #394)
- "Manual sync" #https://github.com/syncthing/syncthing-android/issues/1031
- "Temporarily ignore Sync Restrictions" #https://github.com/syncthing/syncthing-android/issues/769
- "Enhancement. Force sync button in the Android app" #https://github.com/syncthing/syncthing/issues/4861

Requested by:
@felixwiemuth
@nelsonblaha
@grwlf
@sephore
@ymage
@rubenbe
@sojusnik
@vontrapp
@alok0
@Mannshoch

Testing:
- Verified working on AVD 9.x at commit https://github.com/Catfriend1/syncthing-android/pull/443/commits/ac9c3102c01b146ac79dadcd7b355c05f7fa09e3 and on AVD 7.x (Nexus One).

### CODE REVIEW

**Comment by Catfriend1** [comment]
Here's a qick preview:
image

**Comment by felixwiemuth** [comment]
Nice to see that something like this is eventually coming.

Are these buttons actually meant to be a 3-options toggle switch? Or are the two on the right rather one-time actions? How are the semantics exactly?

While you are at it, would it be difficult to also add launcher shortcuts (widgets or the newer actions one can perform when long-clicking on an app's icon) which would initiate those actions? The idea is that one can as quickly as possible manually force a sync.

Thanks!

**Comment by Catfriend1** [comment]
Reviewing ...

**Comment by Catfriend1** [comment]
@felixwiemuth 
= Are these buttons actually meant to be a 3-options toggle switch? =
Exactly that.

= While you are at it, would it be difficult to also add launcher shortcuts (widgets or the newer actions one can perform when long-clicking on an app's icon) which would initiate those actions? The idea is that one can as quickly as possible manually force a sync. =
Once this functionality is in and proved working, it would be easy to add launcher widgets and a quick settings toggle. The quick settings toggle is already on my dev plan.

**Comment by Catfriend1** [comment]
@arodland Hi, does this feature of Syncthing-Fork help you out?

**Comment by arodland** [comment]
@Catfriend1 yes. Not exactly what I had in mind, but certainly good enough to do the job. Thanks :)

**Pull request merged**
